### ISSUE TITLE
mp.resume_all() has been deprecated upstream

### ISSUE THREAD

**Issue by hejops** [Feqzz/mpv-lastfm-scrobbler#1]
`mp.resume_all()` has been deprecated upstream — refer to:

https://github.com/mpv-player/mpv/blob/2f747341f99d9f8697303be01c67ae3b3437cd18/RELEASE_NOTES#L51

For my use cases, removing those calls doesn't affect the script.

**Comment by Feqzz** [comment]
Thank you for making me aware. I have removed the function calls in 43178a47b7d8a44edfe8417b1f9ce4a2f4477775.
